services:
  mongodb:
    image: mongo:latest
    container_name: aao_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  server:
    platform: linux/amd64
    container_name: aao_server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5001:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/aao_system
      - JWT_SECRET=aao_secret_key_docker_test
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    restart: on-failure

  client:
    container_name: aao_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    stdin_open: true
    tty: true
    restart: on-failure

volumes:
  mongo-data: